### PR TITLE
new-dom-fix

### PR DESCRIPTION
**Pull request by paulojblack**
Changed the xpaths to suit the new dom. They threw in some sneaky extra spaces, presumably they got sick of people beating down their door for this tutorial.

### CODE REVIEW

**Comment by Granitas** [comment]
I'm not sure if changing the `xpath()` approach to `css()` is a good idea. Throughout the whole tutorial we use xpath and xpath seems to be default. Also I'm pretty sure css is being converted to xpath anyways so css selectors aren't even a real thing #xpathmasterrace :)

**Comment by redapple** [comment]
@Granitas , indeed, CSS selectors are converted to XPath. And XPath is more powerful as you can go in any direction, even upwards, and have complex predicates and use string functions.
Though, the killer feature of CSS Selectors to me is `.classname`, which is quite handy here for dmoz. The extra trailing space here:
```
<div class="site-item ">
```
is easy to get wrong.
The equivalent XPath is so ugly IMO (`descendant::div[@class and contains(concat(' ', normalize-space(@class), ' '), ' site-item ')]`)
`:nth-*(odd/even)` is also nice and shorter than with XPath, yet less useful.

Probably dmoz is not the best website to use for an XPath tutorial in the end.

**Comment by Granitas** [comment]
@redapple Yeah, it's really bothersome that xpath doesn't have a default alias for such class detection. However you can extend the xpath functions for lxml really easily as per http://lxml.de/extensions.html. 
Cool gist for has-class behaviour: https://gist.github.com/shirk3y/458224083ce5464627bc
Though I'm pretty sure that's beyond the scope of this tutorial but maybe this is worth mentioning somewhere in the docs that xpath can be extended with python functions in such way? Maybe even populate default scrapy namespace with some shortcuts as the has-class from above?

**Comment by redapple** [comment]
There's an open issue about this on parsel: https://github.com/scrapy/parsel/issues/13

**Comment by eliasdorneles** [comment]
Hey @paulojblack, thanks so much for the PR!
Sorry for taking long to handle this -- your changes were incorporated in #21 which also added PY3 compatibility.
Thanks a bunch! :+1: :+1:

**Pull request closed without merging**
